country: China

server:
  port: 80
  # port: ${random.int(2000,8000)}

baseDir: /Users/username
tempDir: ${baseDir}/documents

users:
  -
    name: David
    age: 23
  -
    name: Shie
    age: 20


# datasource config
datasource:
  url: jdbc:mysql://localhost/springboot_db
  driver: com.mysql.jdbc.Driver
  username: root
  password: root123